spring.datasource.url=jdbc:postgresql://localhost:5432/autodrive_db
spring.datasource.username=autodriver_user
spring.datasource.password=Sua_senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true